### PR TITLE
Added vim integration and improved zsh plugin

### PR DESCRIPTION
**Pull request by charlesnchr**
I was running into the issue when using the zsh plugin that `autojump` would output a file instead of a directory, which causes the plugin to return an error. I think it's more useful for ranger to open and simply select the file.

I have also included a vim integration that I have found useful, which ties in with both autojump and zsh. I include this extra layer of integration for vim users.

### CODE REVIEW

**Comment by fdw** [comment]
Hey, thanks for your ideas! 🙂

Unfortunately, I have some second thoughts about some changes: First, and most importantly, `autojump` is supposed to only work with directories. The plugin for Vim, on the other hand, also adds files to the DB. This is why the zsh plugin needs those changes you suggested.
But I'm not convinced that unsupported usage of `autojump` should be encouraged. I'm not even sure what `autojump` itself does if a file is the best match... does it work? From what I can see, it looks like it's printing an error?

Secondly, can you please describe to me what `cd -r` adds in ranger? I have never used it before, and the help wasn't too forthcoming.

Finally, you removed the warning about maintenance mode in the readme. However, that is still very true - I personally haven't used `autojump` in quite some time (I migrated to [zoxide](https://github.com/ajeetdsouza/zoxide)) and don't plan to invest too much time into this repo.

**Comment by charlesnchr** [comment]
Good point about possibly using `autojump` in an unspported way. There is however nothing wrong with using `autojump` for files too, in fact I personally find it very useful like that and it's the whole premise of the vim plugin https://github.com/trotter/autojump.vim. The problem as you say is when running `j [keyword that gives file]`, because it is expecting a directory, thus returning an error, but `autojump` as a command works well for files.

So `autojump` is well-suited to be used with CLI tools that can handle both files or directories, such as vim or ":cd" in Ranger — as well as the updated zsh function, `r`, which has a conditional `--selectfile`.

The `cd -r` in Ranger is not documented I believe, but it appears in the source code, https://github.com/ranger/ranger/blob/master/ranger/config/commands.py, and it simply makes Ranger able to also handle a file input, i.e. `cd -r FILENAME` is well-defined in that Ranger then selects the file and in the parent folder.

Oh, and I didn't mean for this pull request to not have the Maintainance warning, I just removed it when I forked 😅 Anyway, I understand your reservation about the pull request, happy to just use my fork going forward. I might also give Zoxide another try at some point, but autojump.vim is just neat imo 🙂

**Comment by fdw** [comment]
Hi! Did you close the PR on purpose? If so, I hope it wasn't because of my silence - I was just busy with other stuff 🙂
I'm still open for your arguments (in fact, you started to convince me 😉 ). So, feel free to re-open, if you want!

**Comment by charlesnchr** [comment]
Hi @fdw. 

Woops, I didn't know the changes I did on my fork yesterday would be tracked here. I was debugging why antigen package manager did not work with the plugin. Turns out it is just because by default the branch name is assumed to be master and not main. I deleted the main branch in my fork, which has cancelled the pull request.

I have been using this integration of autojump, ranger, zsh and vim more and more over the past few days, and I really like it! I forgot to thank you for the original plugin, nice work. 

I'm happy to make a new pull request — I'll add an instruction on correct antigen installation and I will restore the maintainance warning.

**Pull request closed without merging**
